BUGFIX: Migrate media browser icons
neos/neos-development-collection pull request #3091
Opened 2020-08-24 15:07 UTC by kdambekalns

In Neos prior to 4.1, the media browser uses PNG resources to show thumbnails for non graphical documents from `…/Public/Icons/`, like `ppt.png`. In 4.1 the PNG ressources were removed and replaced by SVG resources from `…/Resources/Public/IconSets/vivid/`. When you add new files after the upgrade, the valid SVG resources are used, but old assets still refer to their old resources, which are missing. As a result, the media browser shows the rotating “loading” icon for these old documents.

This adds Doctrine migrations to replace the old with the  new icons in the database.

Fixes #2341

2020-08-24 15:07 UTC, kdambekalns commented
/cc @DrillSergeant

2020-08-24 19:59 UTC, daniellienert approved these changes
Thanks for taking care Karsten!

2020-08-24 20:02 UTC, daniellienert requested changes

2020-08-24 20:02 UTC, daniellienert commented on Neos.Media/Migrations/Mysql/Version20200823164700.php
> +use Doctrine\Migrations\AbstractMigration;
```suggestion
use Doctrine\DBAL\Migrations\AbstractMigration;
```
Changed to the abstractMigration of the used Doctrine Version

2020-08-24 20:02 UTC, daniellienert commented on Neos.Media/Migrations/Postgresql/Version20200823164701.php
> +use Doctrine\Migrations\AbstractMigration;
```suggestion
use Doctrine\DBAL\Migrations\AbstractMigration;
```

2020-08-25 09:48 UTC, daniellienert approved these changes

2020-08-25 09:51 UTC, merged

2020-08-28 15:10 UTC, kdambekalns commented
… and using `REPLACE` would have been way easier. 😬🤷‍♂️