BUGFIX: Respect already definded attributes in Neos.Neos:ConvertUris
neos/neos-development-collection pull request #3152
Opened 2020-10-29 13:03 UTC by jonnitto

This will solve issue #2942

* The `rel` value get merged with existent`rel` attributes
* If a value already exists, it will not get overridden. Example `<a href="https://external.site" target="external">` the target stays `external`
* When you set the external target to something different (e.g. `'external'`) or disable it with false, the `rel` attribute will still be set

2020-10-29 17:37 UTC, jonnitto commented
You can use this prototype to test the behavior:

```
prototype(Foo.Bar:Test.ConvertUris) < prototype(Neos.Fusion:Component) {
    documentNode = ${q(site).find('[instanceof Neos.Neos:Document]').get(0)}
    attributes = Neos.Fusion:DataStructure {
        1 = 'rel="nofollow noopener"'
        2 = 'rel="nofollow"'
        3 = 'target="special"'
    }
    links = Neos.Fusion:DataStructure {
        External = 'https://external.site.com'
        Node = ${'node://' + q(site).find('[instanceof Neos.Neos:Document]').get(0).identifier}
        # Add here a valid asset identifier
        Asset = 'asset://07a2bac5-7d24-4c1d-b7c4-504c1e5d66e6'
    }

    prototype(Neos.Neos:ConvertUris) {
        externalLinkTarget = 'external'
        resourceLinkTarget = 'asset'
    }

    renderer = Neos.Fusion:Component {
        markup = afx`
            <Neos.Fusion:Loop items={props.links} itemName='href' itemKey='label'>
                <h2>{label} links</h2>
                <ul>
                    <li><a href={href}>{label} link</a></li>
                    <Neos.Fusion:Loop items={props.attributes}>
                        <li>
                            {'<a href="' + href + '" ' + item + '>' + label + ' link with <code>' + item + '</code></a>'}</li>
                    </Neos.Fusion:Loop>
                </ul>
            </Neos.Fusion:Loop>
        `
        renderer = afx`
            <h1>Default behavior</h1>
            <Neos.Neos:ConvertUris value={props.markup} />
            <h1>Absolute</h1>
            <Neos.Neos:ConvertUris value={props.markup} absolute={true} />
            <h1>Force conversion</h1>
            <Neos.Neos:ConvertUris value={props.markup} forceConversion={true} />
        `
    }
}
```

2020-10-30 14:08 UTC, jonnitto commented
@bwaidelich I've tested this code on several sites where I fixed this issue with `@process` before. Didn't break anything, even when I left the `@process` code as it was.

2020-10-30 15:16 UTC, jonnitto commented
Sorry for the force-push. I had to rename a commit message

2020-10-30 15:59 UTC, bwaidelich requested changes
Thanks a lot for this contribution and sorry for the -1.
Let me explain:
I found some nitpicky issues and commented them inline, but I have some more profound concerns with this one:
This code is basically executed on every piece of content that we output via Neos so it has to be **rock solid**. I was surprised to see that we use Regex to "parse" HTML since that is almost [never a good idea](https://stackoverflow.com/a/1732454).
I can already see dozens of cases where our current implementation would fail and I really wonder why that hasn't exploded before.

Having said that, your change doesn't make things worse of course and I already created a separate issue for the major overhaul (#3155)..

This should at least get some test coverage though. I'll gladly help with that next week

2020-10-30 16:03 UTC, kdambekalns commented on Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
> +        if (!($this->fusionValue('forceConversion')) && $node->getContext()->getWorkspace()->getName() !== 'live') {
My guess: the cheaper check comes first now.

2020-10-30 16:04 UTC, kdambekalns commented on Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
> +                [$linkText, $linkHref] = $matches;
Array destructuring is a feature that was introduced with PHP 7.1 (back in December 2016)

2020-10-30 20:31 UTC, jonnitto commented on Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
> +        if (!($this->fusionValue('forceConversion')) && $node->getContext()->getWorkspace()->getName() !== 'live') {
Yep. I explained it in the commit message

2020-10-30 20:51 UTC, jonnitto commented on Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
> +                if ($target && is_string($target)) {
I've done it now with `is_string($target) && strlen($target) !== 0`

2020-10-30 20:53 UTC, jonnitto commented on Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
> +
Done by prettier

2020-10-30 21:00 UTC, jonnitto commented on Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
> +     * @return string
I add comments, removed the parameter $multipleArguments, and handle this in the function itselff

2020-11-09 08:38 UTC, kdambekalns commented on Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
> +
Doesn't matter, I see this a lot with code cleanup and I am not even sure it's not part of some (upcoming) PSR…

2020-11-09 08:40 UTC, kdambekalns commented
@jonnitto Reviews are nice, but as long as unit tests fail, only of limited use… 😬

2020-11-12 15:01 UTC, bwaidelich reviewed
Thanks for taking care..
I'm still a bit concerned with this one since it's such a central part of the rendering and slight behavioral changes could lead to subtle effects..
The amount of tests that had to be adjusted shows this.

In any case I'll remove that from the Neos 6.0 board since it is targeted for 4.3

2020-11-26 07:08 UTC, jonnitto commented on Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
> +
I removed the blank line, so it fits the other files

2020-11-26 07:11 UTC, jonnitto commented on Neos.Neos/Tests/Unit/Fusion/ConvertUrisImplementationTest.php
> +                return 'http://localhost/replaced/uri/01';
Because http://replaced would be recognized as external URL.

2020-11-27 08:38 UTC, kdambekalns approved these changes
It seems that before this change we even had wrong behaviour that we explicitly expected in our tests. 🙈

2020-11-27 11:28 UTC, jonnitto commented
> It seems that before this change we even had wrong behavior that we explicitly expected in our tests. 🙈

Yep. It's was kind of creepy as I recognize this 😜

2020-11-28 07:24 UTC, markusguenther approved these changes
Thanks for that fix Jon. I just need to adjust your example for testing ;)

```
{'<a data-target="do not touch" data-rel="do not touch" href="' + href + '" ' + item + '>' + label + ' link with <code>' + item + '</code></a>'}
```

❤️

2020-11-28 11:55 UTC, merged