BUGFIX: Search by defined property is not possible
neos/neos-development-collection pull request #3165
Opened 2020-11-08 20:28 UTC by lars85

- `findByProperties` should not search for a node identifier.
- `$term` in `foreach ($searchTerm as $term) {` has overwritten `$term` from methode signature. Because of that it was not possible to pass an array to `$this->nodeDataRepository->findByProperties`

2020-11-09 08:20 UTC, markusguenther reviewed
Thanks @lars85 for this PR. It looks good by reading, but would be nice if some one else can verify that it is not breaking something. But as it is not used somewhere it looks like kind of dead code.

2020-11-16 08:23 UTC, daniellienert commented on Neos.Neos/Classes/Domain/Service/NodeSearchService.php
> +    public function findByProperties($term, array $searchNodeTypes, Context $context, NodeInterface $startingPoint = null): array
That does not match the current `NodeSearchServiceInterface`

2020-11-27 09:07 UTC, kdambekalns requested changes
Good find with the overridden `$term`, but I'd like to see this solved differently.

- keep the exception - or do an early return - because the method should not be used to find "everything" (which is what I'd expect for an empty searach term)
- keep the node identifier search! "does not seem to be used" is a bit lax for justification
- pass `$searchTerm` (not `$term`) to the `NodeDataRepository` to fix the actual bug

2021-11-24 21:46 UTC, kdambekalns commented
Closing in favor of #3429

2021-11-24 21:46 UTC, closed without merging