FEATURE: Allow NodeTypes to be defined in hierarchical folders
neos/neos-development-collection pull request #3332
Opened 2021-04-15 13:32 UTC by bwaidelich

This feature allows `NodeType.*.yaml` files to be put into nested
folders underneath `<Package-Root>/NodeTypes`:

```
Packages
  Some.Package
    Configuration
      NodeTypes.yaml (still supported!)
    NodeTypes
      Foo
        Bar.yaml (new)
```

Resolves: #3000

2021-04-15 13:33 UTC, bwaidelich commented
**NOTE:** This is a draft still because it relies on https://github.com/neos/flow-development-collection/pull/2449 and is missing tests still

2021-04-15 14:03 UTC, mficzel commented
Not sure we should rush this, i would love to discuss first wether there is a way to colocate NodeTypes with the fusion integration or vice versa.

2021-04-15 14:22 UTC, gjwnc commented
@mficzel As a note, the missing PR, @bwaidelich mentioned, allows you to put the Configuration anywhere you want. Currently, flow has the configuration locations kinda hardcoded because of the currently implemented configuration processors, tells the configuration manager where the config is located and how it should be merged.

2021-04-15 14:37 UTC, bwaidelich commented
> we should at least think about this before.

Absolutely! I replied in the issue (https://github.com/neos/neos-development-collection/issues/3000#issuecomment-820476124)

2021-07-27 15:12 UTC, Sebobo commented
Tested with https://github.com/neos/flow-development-collection/pull/2449 and it works perfectly! ❤️

2021-07-27 15:13 UTC, Sebobo requested changes
Approved but we can only merge it when https://github.com/neos/flow-development-collection/pull/2449 is merged.

2021-08-04 12:49 UTC, jonnitto approved these changes
Tested it, and it works ❤️

2021-08-09 12:46 UTC, bwaidelich commented on Neos.ContentRepository/Classes/Configuration/NodeTypesLoader.php
> +    public function __invoke(array $packages, ApplicationContext $context): array
```suggestion
    public function load(array $packages, ApplicationContext $context): array
```

2021-08-09 18:14 UTC, bwaidelich commented
@Sebobo would you revoke your -1 now that neos/flow-development-collection#2449 is merged?

Regarding the tests: They fail because they still pull in an old version of Flow apparently (`Locking neos/flow-development-collection (7.1.x-dev 5358d96)`). @albe do you have an idea on how to solve that?

2021-08-10 07:33 UTC, Sebobo approved these changes

2021-08-10 10:13 UTC, albe commented
> Regarding the tests: They fail because they still pull in an old version of Flow apparently (`Locking neos/flow-development-collection (7.1.x-dev 5358d96)`). @albe do you have an idea on how to solve that?

Very odd - the neos dev distribution is installed witth the proper dev-master and in turn requires `flow-development-collection @dev` (https://github.com/neos/neos-development-distribution/blob/master/composer.json#L20) - why composer resolves that to 7.1.x-dev instead of dev-master is not clear to me. Maybe the solution would be to also clone the flow dev-collection in the build pipeline and add a local path repository like for the neos dev-collection. That would make sure that always the matching flow branch is used in builds independent of what composer thinks it should resolve to. The biggest issue is the version mismatch before "Seven", which would require some odd logic, but maybe it's good enough to adjust the build in 7.0+ only?

See https://github.com/neos/neos-development-collection/blob/master/.github/workflows/build.yml#L115-L116

2021-08-11 10:57 UTC, kdambekalns commented
Probably 7.1.x-dev is chosen over dev-master because it's the "better" match during dependency resolving. Maybe even our dreaded guzzlehttp/psr7 issue?

2021-08-11 10:58 UTC, kdambekalns approved these changes
Looks good by reading.

2021-08-11 10:58 UTC, merged