Fix: Only document Nodes should appear in Breadcrumb
neos/neos-development-collection pull request #3386
Opened 2021-07-28 09:04 UTC by paavo

When rendering the Breadcrumb-Menu in a Content Node, the Content-Node itself is added to the Menu.

**What I did**
Updated BreadcrumbMenuItems to only use DocumentNodes. 

**How I did it**
Replacted `q(node).add(...)` with `q(documentNode).add(...)`

**How to verify it**
Use BreadcrumbMenuItems inside a Content Node. 

**Checklist**

- [x] Code follows the PSR-2 coding style
~~- [ ] Tests have been created, run and adjusted as needed~~
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

2021-07-28 18:05 UTC, jonnitto commented
I think, this should go into the 5.3 branch

2021-07-28 18:07 UTC, jonnitto requested changes
@paavo Could create the PR against the 5.3 branch? If I change the base in Github, I'll get thousands of commits ;-)

2021-07-29 09:01 UTC, paavo commented
> Could create the PR against the 5.3 branch? If I change the base in Github, I'll get thousands of commits ;-)
Maybe its the easiest to create a new commit @jonnitto 
i'll go for it..

2021-07-29 09:04 UTC, paavo commented
Replaced with https://github.com/neos/neos-development-collection/pull/3389

2021-07-29 09:04 UTC, closed without merging