Feature: AFX shorthand for @if and @process / generate keys
neos/neos-development-collection pull request #3428
Opened 2021-09-12 18:38 UTC by mhsdesign

resolves: https://github.com/neos/fusion-afx/issues/29

Automatically generates key for `@if` and `@process` when no one is specified.
Multiple meta properties transpile to: '@if.if_0' and '@if.if_1'

**Demo**
```html
# afx
<Vendor.Site:Prototype @if={eel1} image.@if={eel2} />

```

```ts
# fusion
Vendor.Site:Prototype {
    @if.if_0 = ${eel1}
    image.@if.if_0 = ${eel2}
}
```

**What I did**
before the attributes are handed into the big loop and converted to fusion, some keys are modified.
Each attribute key string that ends with either `@if` or `@process` will get an auto generated key.

**Improvements i did not do yet.**
I think the function `generatePathForShorthandFusionMetaPath` could be integrated in the for loop succeeding it (we would save one loop then) but i did not want to create spaghetti yet. (The generation relies on a `global` index list wich will decide the next number - easier would be a random number or a not path aware incrementing count. (a simple i++))

btw watch out:
The global editorconfig from neos removes wanted whitespaces from the AfxService.php...

**How to verify it**
added some tests ; )

**Checklist**

- [x] Tests have been created, run and adjusted as needed

2021-11-06 14:52 UTC, jonnitto requested changes

2021-11-06 14:52 UTC, jonnitto commented on Neos.Fusion.Afx/Classes/Service/AfxService.php
> +
```suggestion
            if ($attribute['type'] !== 'prop') {
                continue;
            }

```

2021-11-06 14:52 UTC, jonnitto commented on Neos.Fusion.Afx/Tests/Functional/AfxServiceTest.php
>  </h1>
I think this need to be reverted

2021-11-06 14:52 UTC, jonnitto commented on Neos.Fusion.Afx/Tests/Functional/AfxServiceTest.php
> +    lines
I think this need to be reverted

2021-11-08 10:41 UTC, gerhard-boden commented
> BTW: I consider the original argument of @gerhard-boden not that important nowadays. If you rely on the exact fusion pathes afx generates you are probably using it wrong anyways. Especially if anyone overrides fusion pathes generated by afx from the outside.

Whoa it's been a while since I composed that comment 😂  But I think it wasn't about overriding, but simply seeing what AFX argument (or path) caused the site to crash. Debugging named paths has always been easier for me.

Since the majority of more active AFX users than me seems to be okay with the dynamic approach it could easily be that I'm "using it wrong", so don't see my comment as a blocker in any way 😊

2021-11-15 07:12 UTC, mficzel commented
Pretty sure the ide is applying .editorconfig rules to tests that verify that afx works with slightly messy code aswell.

I had to change the .editorconfig temporary to work on those tests.

2021-11-15 07:14 UTC, mficzel commented
#

2021-11-15 07:14 UTC, mficzel commented
Sorry for closing and opening, cellphones and GitHub do not mix well

2021-11-21 20:37 UTC, mhsdesign commented on Neos.Fusion.Afx/Classes/Service/AfxService.php
> +
done

2021-11-21 20:37 UTC, mhsdesign commented on Neos.Fusion.Afx/Tests/Functional/AfxServiceTest.php
>  </h1>
thx done ;)

2021-11-21 20:37 UTC, mhsdesign commented on Neos.Fusion.Afx/Tests/Functional/AfxServiceTest.php
> +    lines
erledigt ^^

2021-11-21 20:41 UTC, mhsdesign commented
okay all green now and stuff fixed.
Can we merge this soon before feature freeze and then we can (i will) address #3463

2021-11-22 09:15 UTC, markusguenther commented
@jonnitto as the requested changes are outdated. Is this fine for you?

2021-11-22 10:33 UTC, mficzel approved these changes
I like this change, the code looks fine the teste make sense and it worked in my tests.

The readme could be adjusted but this may also happen later.

2021-11-22 12:16 UTC, jonnitto approved these changes

2021-11-22 12:16 UTC, merged

2021-11-22 12:17 UTC, jonnitto commented
@mficzel Please add only issues to the project board… This makes it easier for us, to track the current state