TASK: Add documentation of range slider
neos/neos-development-collection pull request #3537
Opened 2021-12-14 13:31 UTC by jonnitto

Add documentation  for newly added range slider https://github.com/neos/neos-ui/pull/2986

2021-12-16 11:13 UTC, mhsdesign requested changes
just some typo stuff (den text durch https://languagetool.org/de geschleust)

2021-12-16 11:13 UTC, mhsdesign commented on Neos.Neos/Documentation/References/PropertyEditorReference.rst
> +  The value gets displayed beside the current value, as well after the minmal value (only if ``minLabel`` is not set) and after the maximal value (only if ``maxLabel`` is not set)
```suggestion
  The value gets displayed beside the current value, as well after the minimal value (only if ``minLabel`` is not set) and after the maximal value (only if ``maxLabel`` is not set).
```

2021-12-16 11:13 UTC, mhsdesign commented on Neos.Neos/Documentation/References/PropertyEditorReference.rst
> +	The lowest value in the range of permitted values. This value must be less than or equal to the value of the max attribute
```suggestion
	The lowest value in the range of permitted values. This value must be less than or equal to the value of the max attribute.
```

2021-12-16 11:13 UTC, mhsdesign commented on Neos.Neos/Documentation/References/PropertyEditorReference.rst
> +	If set, this value is displayed instead of the maximum value
```suggestion
	If set, this value is displayed instead of the maximum value.
```

2021-12-16 11:13 UTC, mhsdesign commented on Neos.Neos/Documentation/References/PropertyEditorReference.rst
> +	If set, this value is displayed instead of the minimum value
```suggestion
	If set, this value is displayed instead of the minimum value.
```

2021-12-16 11:13 UTC, mhsdesign commented on Neos.Neos/Documentation/References/PropertyEditorReference.rst
> +If a certain value should be entered the current value can also be clicked to enter the desired value directly.
```suggestion
If a certain value should be entered, the current value can also be clicked to enter the desired value directly.
```

2021-12-16 11:13 UTC, mhsdesign commented on Neos.Neos/Documentation/References/PropertyEditorReference.rst
> +The minimum, maximum and step size can be defined. Additionally a unit label as well as a special label for the minimum and maximum value can be defined.
```suggestion
The minimum, maximum and step size can be defined. Additionally, a unit label as well as a special label for the minimum and maximum value can be defined.
```

2021-12-18 10:30 UTC, mhsdesign commented on Neos.Neos/Documentation/References/PropertyEditorReference.rst
> +  The value gets displayed beside the current value, as well after the minimal value (only if ``minLabel`` is not set) and after the maximal value (only if ``maxLabel`` is not set).
```suggestion
  The value gets displayed beside the current value, as well after the minimal value (only if ``minLabel`` is not set) and after the maximal value (only if ``maxLabel`` is not set). (The unit is just a visual indicator and will not be added to the resulting property value.)
```

2021-12-21 14:57 UTC, markusguenther approved these changes
👍

2021-12-26 16:28 UTC, mhsdesign approved these changes

2021-12-26 16:28 UTC, merged