[FEATURE] allow sorting of users by last logged in date
neos/neos-development-collection pull request #3629
Opened 2022-03-01 12:16 UTC by batabana

This change would add the possibility to sort the users in the backend module Administration > User Management by their last logged in date. This can be done by clicking on the "Last Login" Header, similarly to clicking on "Last modified" in the 
 media module.

<img width="1361" alt="grafik" src="https://user-images.githubusercontent.com/36864084/156166993-c9a047af-1471-4efc-a4e1-a60b3855fee3.png">

2022-03-24 08:20 UTC, markusguenther approved these changes
Thanks for the improvement @batabana 💚

2022-05-03 10:47 UTC, daniellienert requested changes

2022-05-03 10:47 UTC, daniellienert commented on Neos.Neos/Classes/Domain/Repository/UserRepository.php
> +    public function findAllOrderedByLastLoggedInDate(bool $sortDescending): QueryResultInterface
I would rather add a generic method `findAllOrdered(string $field, string $direction)` that takes the field as parameter

2022-05-03 10:47 UTC, daniellienert commented on Neos.Neos/Classes/Domain/Repository/UserRepository.php
> +    const SORT_DIRECTION_DESC = 'DESC';
This constant is already defined as `\Neos\Flow\Persistence\QueryInterface::ORDER_DESCENDING` - would make sense to use that one.

2022-05-03 10:47 UTC, daniellienert commented on Neos.Neos/Classes/Domain/Repository/UserRepository.php
> +    const SORT_DIRECTION_DESC = 'DESC';
This constant is already defined as `\Neos\Flow\Persistence\QueryInterface::ORDER_DESCENDING` - would make sense to use that one.

2022-05-03 10:47 UTC, daniellienert commented on Neos.Neos/Classes/Domain/Service/UserService.php
> +            return $this->userRepository->findAllOrderedByLastLoggedInDate($sortDirection === UserRepository::SORT_DIRECTION_DESC);
Instead of passing a boolean and later converting that boolean to DESC / ASC, it would make sense to pass the direction directly

2022-05-03 10:47 UTC, daniellienert commented on Neos.Neos/Classes/Domain/Service/UserService.php
> +            return $this->userRepository->findAllOrderedByLastLoggedInDate($sortDirection === UserRepository::SORT_DIRECTION_DESC);
Instead of passing a boolean and later converting that boolean to DESC / ASC, it would make sense to pass the direction directly

2022-05-03 10:47 UTC, daniellienert commented on Neos.Neos/Resources/Private/Templates/Module/Administration/Users/Index.html
> +								<f:if condition="{sortBy} === 'LastLoggedIn'">
With this it is not possible anymore to sort the users by account after sorting it by date. We should add the same options for account as well.

2022-05-03 10:47 UTC, daniellienert commented on Neos.Neos/Resources/Private/Templates/Module/Administration/Users/Index.html
> +								<f:if condition="{sortBy} === 'LastLoggedIn'">
With this it is not possible anymore to sort the users by account after sorting it by date. We should add the same options for account as well.

2022-05-03 16:55 UTC, daniellienert commented
Hey @batabana, 
thank you very much for your contribution! We are currently on the Neos sprint and one of the attendees, @crydotsnake picked your PR, fixed the issues and added the possibility to also sort the list by Name and accountName. 

Thats why I close this PR in favor of https://github.com/neos/neos-development-collection/pull/3709

2022-05-03 16:55 UTC, closed without merging