TASH: Seperate parser cache and parser cache flusher
neos/neos-development-collection pull request #3691
Opened 2022-04-03 18:36 UTC by mficzel

Separate partial cache flushing from partial caching.

resolves: https://github.com/neos/neos-development-collection/issues/3685
related: https://github.com/neos/neos-development-collection/pull/3659
replaces: https://github.com/neos/neos-development-collection/pull/3688

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

2022-04-03 19:06 UTC, mhsdesign requested changes
Many thanks for this PR ^^

i see what you have done with all this flow magic xD ... but it might be worth to take a simpler approach like done in the `FileMonitorListener` (eg, injecting all dependencies + cache manually ...) this way we dont need the closure in the bootstrap and dont need the flow lifecylce methods - though i consider it not so clean to not read the cache from yaml but inject it hardcoded ...

2022-04-03 20:15 UTC, mficzel commented
Adjusted as requested. While this change removes the error there seems to be a race condition when php code and fusion is changes at the same time.

2022-04-03 21:07 UTC, mficzel commented
@mhsdesign i think i got it. Works now basically the same as the FileMonitor for the FusionContentCache and seems to avoid those race conditions nicely.

2022-04-04 06:22 UTC, mhsdesign approved these changes
I can confirm that this works nicely and fixes the bug described in https://github.com/neos/neos-development-collection/issues/3685

2022-04-04 08:50 UTC, kdambekalns approved these changes

2022-04-04 09:00 UTC, merged