FEATURE: add sorting in user management backend module
neos/neos-development-collection pull request #3709
Opened 2022-05-03 15:07 UTC by crydotsnake

If you go to the User Management Backend Module: Administration -> User Management, it's now possible to sort by the Name, The Accounts, and the last login by clicking on the specific header.

![demo](https://user-images.githubusercontent.com/39345336/166480201-c1c43309-0c9d-453f-9722-aca812809b12.gif)

2022-05-03 16:20 UTC, daniellienert requested changes

2022-05-03 16:20 UTC, daniellienert commented on Neos.Neos/Classes/Domain/Repository/UserRepository.php
> +    const SORT_DIRECTION_DESC = 'DESC';
Is this still in use?

2022-05-03 16:20 UTC, daniellienert commented on Neos.Neos/Classes/Domain/Repository/UserRepository.php
> +        return $this->findAllOrdered('accountIdentifier');
needs additional table alias

2022-05-03 16:51 UTC, daniellienert approved these changes

2022-05-04 19:10 UTC, mficzel approved these changes
I like, looking good and works as expected.

2022-05-04 19:11 UTC, merged