TASK: prevent first array element from being accessed via $context
neos/neos-development-collection pull request #3723
Opened 2022-05-04 14:25 UTC by crydotsnake

This pull request fixes the issue #3624

2022-05-04 18:33 UTC, daniellienert commented on Neos.ContentRepository/Classes/Eel/FlowQueryOperations/ChildrenOperation.php
> +        return is_array($context) && (count($context) === 0 || reset($context) instanceof TraversableNodeInterface);
```suggestion
        return is_array($context) && reset($context) instanceof TraversableNodeInterface;
```

2022-05-04 18:34 UTC, daniellienert requested changes
Please adjust the rewritten conditions to the original ones

2022-05-05 06:49 UTC, daniellienert approved these changes

2022-05-05 09:38 UTC, mficzel reviewed
We have to reflect about wether the flow context can be traversable as it is allowed in 

https://github.com/neos/flow-development-collection/blob/master/Neos.Eel/Classes/FlowQuery/FlowQuery.php#L131

2022-05-05 11:18 UTC, mficzel reviewed
We should discuss wether this could/should be a bugfix and which version should be targeted

2022-05-05 15:02 UTC, daniellienert requested changes

2022-05-05 15:02 UTC, daniellienert commented on Neos.ContentRepository/Classes/Eel/FlowQueryOperations/CanEvaluateNodeContextTrait.php
> +    public function checkContextForTraversableNodeInterface($context)
return value type is missing

2022-05-05 18:35 UTC, mficzel commented on Neos.ContentRepository/Classes/Eel/FlowQueryOperations/CanEvaluateNodeContextTrait.php
> +    public function checkContextForTraversableNodeInterface($context)
added as requested

2022-05-05 18:35 UTC, mficzel commented on Neos.ContentRepository/Classes/Eel/FlowQueryOperations/CanEvaluateNodeContextTrait.php
> +    public function checkContextForTraversableNodeInterface($context)
added as requested

2022-05-05 18:37 UTC, mficzel commented on Neos.ContentRepository/Classes/Eel/FlowQueryOperations/FindOperation.php
> +        if (is_iterable($context)) {
That operation had its own logic before that checked every item. That is even checked by a functional test so we assumed this was really intended. 

Also this one used Domain/Model/NodeIntface where the traits use the contentGraphNode/TravesableNodeInterface

2022-05-05 18:40 UTC, mficzel commented on Neos.ContentRepository/Classes/Eel/FlowQueryOperations/CanEvaluateNodeContextTrait.php
> +    public function checkContextForTraversableNodeInterface($context)
The old code tested for NodeInterface where no Traversal was needed that is why there are two methods. Played with a traversable argument but that looked way more messy.

2022-05-05 18:42 UTC, mficzel commented on Neos.ContentRepository/Classes/Eel/FlowQueryOperations/ContextOperation.php
> -        return count($context) === 0 || (isset($context[0]) && ($context[0] instanceof NodeInterface));
I agree this is slightly different but only contexts that are not iterable (array or traversable) which is not allowed. 
The q function ensures that everything that is not iterable is wrapped into an iterable array.

2022-05-19 12:09 UTC, kdambekalns requested changes
It seems not all checks were replaced with the correct trait method… and I have left a question about the change to the `FindOperation`

Otherwise this looks fine!

2022-05-19 12:09 UTC, kdambekalns commented on Neos.ContentRepository/Classes/Eel/FlowQueryOperations/ContextOperation.php
> -        return count($context) === 0 || (isset($context[0]) && ($context[0] instanceof NodeInterface));
I agree to @mficzel - the behaviour is the same, IMHO.

2022-05-19 12:09 UTC, kdambekalns commented on Neos.ContentRepository/Classes/Eel/FlowQueryOperations/HasOperation.php
> +        return $this->checkContextForNodeInterface($context);
```suggestion
        return $this->checkContextForTraversableNodeInterface($context);
```

2022-05-19 12:09 UTC, kdambekalns commented on Neos.ContentRepository/Classes/Eel/FlowQueryOperations/FindOperation.php
> +        if (is_iterable($context)) {
The trait now has checks for both interfaces - but the checking of all elements warrants this method.

A slight change exists, though: countable empty items will only return true if they are iterable, that was different before. Did you do that on purpose to achieve consistency?

2022-05-19 12:11 UTC, kdambekalns commented
And, by the way: I (too) think this should be a bugfix and be applied to the oldest affected supported branch!

2022-07-13 21:16 UTC, mhsdesign commented on Neos.ContentRepository/Classes/Eel/FlowQueryOperations/CanEvaluateNodeContextTrait.php
> +            return true;
i dont think we need this line.
it would be for the case that $context has no iterations, and in this case why should it pass?

2022-07-13 21:17 UTC, mhsdesign commented
i too think this should be a bugfix - targeting the lowest branch.

2022-07-15 13:13 UTC, closed without merging