FEATURE: Introduce `Neos.Fusion:ActionUri` prototype as a replacement for `Neos.Fusion:UriBuilder`
neos/neos-development-collection pull request #3826
Opened 2022-06-26 16:44 UTC by mficzel

The name  `Neos.Fusion:UriBuilder` stands out from other fusion prototypes because it describes what the prototype does
instead of what will be the result. This contradicts the declarative nature of fusion.

This change adds the prototype `Neos.Fusion:ActionUri` as a 1:1 replacement that implements the same api.

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

2022-07-01 17:11 UTC, kdambekalns submitted a review, later dismissed
Looks good by reading, just a tiny whitespace nitpick.

2022-07-01 17:11 UTC, kdambekalns commented on Neos.Neos/Documentation/References/NeosFusionReference.rst
> +    controller="Backend"
```suggestion
        package="Neos.Neos.Ui"
        controller="Backend"
```

2022-07-14 07:23 UTC, mhsdesign requested changes
Thx i generally like it.

I have two concerns:

# 1

in this super long thread https://github.com/neos/neos-development-collection/pull/3255 it was discussed by various people to use this interface for tag links:

`<TagWith.SpecialLink  class="bg-red" href.someprop="a"  href.otherprop="b" />`

i dont know if this is 100% the best choice, but i think we need to stick to one way of handling it.

you suggested this pattern:

`<TagWith.SpecialLink  class="bg-red" someprop="a"  otherprop="b" />`


-----

# 2

the existing
`<Neos.Fusion:Link.Action />`

and your 

`<Neos.Fusion:ActionLink />`

sound really similar. I would like to avoid have two so similar names at the same time in the codebase.

2022-07-14 07:23 UTC, mhsdesign commented on Neos.Fusion/Resources/Private/Fusion/Root.fusion
> +# uri = Neos.Fusion:Link {
```suggestion
# uri = Neos.Fusion:ActionLink {
```

2022-07-14 07:34 UTC, mficzel commented
@mhsdesign interesting ... did not know about Neos.Fusion:Link.Action and Neos.Fusion:Link.Resource yet. 

... will convert this back to draft until we figure out a way to unconfuse this

2022-07-14 08:52 UTC, mficzel commented
@mhsdesign adjusted the pr and instead of adding a new Neos.Fusion:ActionLink i adjusted the Neos.Fusion:Link.Action to use the Neos.Fusion:ActionUri

Since we never really documented that and the default behavior is equivalent i would consider this still non breaky as it will only behave differently in case someone manipulated the ControllerContext.

@kdambekalns i rerequest your review as this is quite an adjustment.

2022-07-14 09:30 UTC, mhsdesign requested changes
Thanks for documenting everything so well :blue_heart: 

Small changes ...

2022-07-14 09:50 UTC, mficzel commented on Neos.Neos/Documentation/References/NeosFusionReference.rst
> +:useMainRequest: (boolean) If set, the main Request will be used instead of the current one.
That useMainRequest was a leftover from the first approaches that i did not spot during the refactoring. Thanks for fixing

2022-07-14 09:50 UTC, mhsdesign approved these changes
By reading ^^

2022-07-15 12:14 UTC, kitsunet approved these changes

2022-07-15 16:39 UTC, merged