BUGFIX: Fusion Parser ignores non existing context file
neos/neos-development-collection pull request #3834
Opened 2022-07-11 15:01 UTC by gjwnc

In case of missing the Root.fusion file of a site package, the Fusion parser, now, ignores those files.

**Upgrade instructions**

Nothing needs to be done.

**Review instructions**

In a multi site project, it might be, that the Root.fusion does not exist for a site. The filename for the site is created in FusionService::getMergedFusionObjectTree() like
```
$siteRootFusionPathAndFilename = sprintf($this->siteRootFusionPattern, $siteResourcesPackageKey);
```
Because this file is optional, the `stat($contextPathAndFilename)` in the Parser::handleFileInclude() causes an error and aborts parsing with

```
Warning: stat(): stat failed for resource://Some.Package/Private/Fusion/Root.fusion in /var/www/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Fusion_Core_Parser.php line 88
```

This PR fixes this case.

@mhsdesign This PR is not related to the issue we talked in slack today. I just noticed this additional issue during debugging.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

2022-07-11 15:50 UTC, mhsdesign requested changes
thank you. i indeed changed the file checking stat behaviour which previously only was done for globbing but not other include methods: https://github.com/neos/neos-development-collection/blob/57c183981113df7c5eec0bc0cbf92d2f1ff8388a/Neos.Fusion/Classes/Core/Parser.php#L635

i know your current fix i working, but i dont find it clean to disable the cache that way.

i think we need to fix two things:

it wasnt obvious, to us that the error was because a failed stat() call, we need to prevent that and throw more readable errors, in case someone tries to use an invalid path.

we need to stop producing non working fake paths in the fusion service.
eg. only provide the contextPath, if the file is readable.

https://github.com/neos/neos-development-collection/blob/b91861896db98628d435e399e1144919cf77404b/Neos.Neos/Classes/Domain/Service/FusionService.php#L140

2022-07-11 19:20 UTC, kitsunet requested changes
I don't understand how this works, the described case should already be prevented in `\Neos\Fusion\View\FusionView::getMergedFusionObjectTree` by a check for directory AND file, how can this happen exactly? Whatever happens here I think just not caching is probably not the right option, but rather fixing the case "higher" up.

2022-07-12 06:07 UTC, gjwnc commented
> we need to prevent that and throw more readable errors, in case someone tries to use an invalid path.

Hmm, you mean something like this in `Parser::parse()`?
```
if ($contextPathAndFilename && !\is_file($contextPathAndFilename)) {
    throw new Fusion\Exception("given context path and filename does not exist '$contextPathAndFilename'", 1657605723);
}
```

> we need to stop producing non working fake paths in the fusion service.

I partly agree. Currently yes, but I think it might be an interesting feature in the future, if the fusion code is not read from the filesystem but from some remote source? Could be interesting to have something like a central fusion repository? So, virtual paths or some kind of source identifiers might be of interest - and I think we might not be that far away from this possibility. But, yeah, that's another topic.

> only provide the contextPath, if the file is readable.

Currently, yes that makes sense I think, like this in FusionService::getMergedFusionObjectTree, right?
```
$parsedFusion = $this->fusionParser->parse($mergedFusionCode, \is_file($siteRootFusionPathAndFilename) ? $siteRootFusionPathAndFilename : null);
```

2022-07-12 07:22 UTC, gjwnc commented
> I don't understand how this works, the described case should already be prevented in `\Neos\Fusion\View\FusionView::getMergedFusionObjectTree` by a check for directory AND file, how can this happen exactly? 

Neos uses the Neos.Neos FusionView, not the Neos.Fusion FusionView. So, that's where the problems arise.

> Whatever happens here I think just not caching is probably not the right option, but rather fixing the case "higher" up.

I just created another issue #3835 which maybe should be fixed in tandem?

2022-07-12 07:36 UTC, mhsdesign commented
Yes those issues are quite coupled and we need to fix them both in the same run

2022-07-12 08:39 UTC, kitsunet commented
pretty much summed up my thoughts in #3835 I agree a solution for both needs to be found and I guess it's not quite easy :/

2022-07-12 16:07 UTC, gjwnc commented
This can be closed as it might be part of #3835.

A quickfix is to just create the missing Root.fusion for the site package.

2022-07-12 16:07 UTC, closed without merging