BUGFIX: Have FlowQuery operations reliably detect nodes during canEvaluate
neos/neos-development-collection pull request #3838
Opened 2022-07-15 13:11 UTC by kitsunet

When a collection of nodes is referenced some items may become invisible over time or may be deleted. In this case the references may end up with an array that has no key 0. Since this key was used to check wether a flowQuery operation can be applied this could lead to errors.

The change adjusts the detection by looking at using reset to get the first value if the context is an array and by using an foreach that returns in the first cycle for traversables.

Review Instructions

To test this you can use the contentReferences Element in Neos.Demo.

    Create 3 contents
    Create a reference element that references all three
    Hide the content that is selected first
    Apply @process.filterContent( q(value).filter('[instanceof Neos.Neos:Content]').get()) to that.

Without the change in live context no content is shown because the first item is not available live.
This change allows to still proceed with the remaining nodes.

Fixes: #3624

2022-07-15 13:12 UTC, kitsunet commented
This replaces #3723 for the 5.3 branch. Unfortunately some tests do not exist yet in this branch so those commits are missing.

2022-10-23 09:32 UTC, mhsdesign commented
aaaand now we can rebase to 7.3  (sorry) ^^ (maybe those tests will exist then :D)

2022-10-23 09:32 UTC, mhsdesign requested changes
aaaand now we can rebase to 7.3 (sorry) ^^ (maybe those tests will exist then :D)

2022-11-02 10:30 UTC, mhsdesign commented
superseded by https://github.com/neos/neos-development-collection/pull/3946

2022-11-02 10:30 UTC, closed without merging