BUGFIX 3846 Fusion Runtime @process with simple string
neos/neos-development-collection pull request #3847
Opened 2022-07-22 18:10 UTC by mhsdesign

resolved: #3846

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

2022-07-22 18:20 UTC, mhsdesign commented
regression from https://github.com/neos/neos-development-collection/pull/2238/files#diff-a4843c3b40637d5ac469b71012809645cf9d2fa7137aa79d6f7da549fa482f9eR984-R987

2022-07-22 18:22 UTC, mhsdesign commented on Neos.Fusion/Tests/Functional/FusionObjects/ProcessorTest.php
> +        $this->assertMultipleFusionPaths('foo', 'processors/newSyntax/basicProcessor/plainValueOverriddenByPlainValue');
```suggestion
        $this->assertFusionPath('foo', 'processors/newSyntax/basicProcessor/plainValueOverriddenByPlainValue');
```

2022-07-22 21:18 UTC, mficzel commented
Does this work together with @if? I would like to see a test for that case aswell.

Am at a cellphone and cannot really read the full code now?

2022-07-22 21:32 UTC, mhsdesign commented
its not in th @if branch ;) only process related.

btw you likely see everything, its just 1 subtle change

2022-07-22 21:37 UTC, mficzel commented
I mean if the @process has an @if like

@process.foo = “bar”
@process.foo.@if.is = ${…

2022-07-22 21:45 UTC, mhsdesign commented
ah good idea to include it aswell ;)

2022-10-11 10:57 UTC, Sebobo requested changes
Looks good, but can you rebase to 7.3 🙂

2022-10-22 09:51 UTC, mhsdesign commented
@Sebobo @mficzel is adjusted ;)

2022-10-22 14:41 UTC, mficzel approved these changes
Fine by reading. 

Assume this was accidentally introduced with the stopInheritence stuff. Great that there is a test now.

2022-10-24 07:08 UTC, Sebobo approved these changes
Thx

2022-10-24 07:47 UTC, merged