BUGFIX make pagination work with Traversable
neos/neos-development-collection pull request #3891
Opened 2022-09-16 11:01 UTC by ru3fu5z

Warning: array_slice() expects parameter 1 to be array, object given in /tmp/Flow/Development/SubContextddev/Cache/Code/Flow_Object_Classes/Neos_ContentRepository_ViewHelpers_Widget_Controller_PaginateController.php line 124

2022-09-23 10:03 UTC, mhsdesign requested changes

2022-09-23 10:03 UTC, mhsdesign commented on Neos.ContentRepository/Classes/ViewHelpers/Widget/Controller/PaginateController.php
> +            $nodes = (array) array_slice($this->nodes, $offset, $itemsPerPage);
i would much rather change it here in: initializeAction()

`$this->nodes = $this->widgetConfiguration['nodes'];`

something like `if $this->widgetConfiguration['nodes'] instaceof TraversableNodes` ...

2022-09-26 09:24 UTC, mhsdesign commented on Neos.ContentRepository/Classes/ViewHelpers/Widget/Controller/PaginateController.php
> +            $nodes = (array) array_slice($this->nodes, $offset, $itemsPerPage);
also by reading your provided excepfion - your fix wont work i assume. youd need to "transform" the first param to an array but via getIterator()->getArrayCopy() or toArray()

2022-10-17 10:44 UTC, ru3fu5z commented on Neos.ContentRepository/Classes/ViewHelpers/Widget/Controller/PaginateController.php
> +            $nodes = (array) array_slice($this->nodes, $offset, $itemsPerPage);
Thank for your help. I updated the branch with your recommented changes

2022-11-11 15:33 UTC, jonnitto commented
@mhsdesign Do you think 8.2 is the correct branch?

2022-11-11 18:21 UTC, mhsdesign commented
Nope should be 7.3 - im not a fluid gui - but id like to see a test maybe ^^

2023-01-12 17:25 UTC, jonnitto requested changes
@ru3fu5z, thank you for your PR. I think the best is, to close this PR and create a new one, based on the correct branch.

2023-04-29 12:12 UTC, closed without merging