TASK: Tweak note about target branches for PRs
neos/neos-development-collection pull request #3904
Opened 2022-10-02 14:21 UTC by tantegerda1

This removes an explicit mention of the oldest supported branch,
so we don't have to keep updating it.

2022-10-11 08:38 UTC, Sebobo requested changes

2022-10-11 08:38 UTC, Sebobo commented on Readme.rst
> +https://www.neos.io/features/release-process.html), or master for new features.
`master` does not exist anymore. It should say something like `the next minor or major version branch`, but a bit clearer.

2022-10-12 07:14 UTC, Sebobo approved these changes
Looks good to me, thx 🙂

2022-10-20 15:31 UTC, crydotsnake approved these changes

2022-10-20 15:34 UTC, merged