FEATURE: implement checkbox label in workspace module
neos/neos-development-collection pull request #3929
Opened 2022-10-21 10:07 UTC by crydotsnake

**Review instructions**

Currently, in the Workspace module, in the overview, we have a checkbox for selecting all changes. But this checkbox is not marked with a label. For clarity, it is better if it is clearly marked what this checkbox does.

## Screenshots

### Before
![neos-backend-workspace-module-checkbox-without-label](https://user-images.githubusercontent.com/39345336/197170837-7b4e5878-0f76-4ebc-baeb-62320d4522f9.png)

### After
![neos-backend-workspace-module-checkbox-with-label](https://user-images.githubusercontent.com/39345336/197170857-b111a761-037a-4fb7-af02-8bb47380447d.png)

**Checklist**

- [x] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

2022-10-21 10:23 UTC, crydotsnake commented
A small side question: How are the other translations generated? Does that webplate automatically?

2022-10-22 14:36 UTC, mhsdesign approved these changes
... but i have no clue how webplate works at all ^^

2022-10-24 16:47 UTC, kdambekalns requested changes
I'd rather use a different id for the new translation.

Weblate will just do the right thing, any XLIFF file will get the label and translation as needed.

2022-10-24 16:47 UTC, kdambekalns commented on Neos.Neos/Resources/Private/Translations/de/Modules.xlf
> +      <trans-unit id="workspaces.checkbox.label" approved="yes">
```suggestion
      <trans-unit id="workspaces.selectAllCurrentChanges" approved="yes">
```

2022-10-24 16:47 UTC, kdambekalns commented on Neos.Neos/Resources/Private/Templates/Module/Management/Workspaces/Show.html
> +								<th>{neos:backend.translate(id: 'workspaces.checkbox.label', source: 'Modules', package: 'Neos.Neos')}</th>
That is a very generic, err, label. ;) It's not as if there is only one checkbox in the workspace module. May I suggest this:

```suggestion
								<th>{neos:backend.translate(id: 'workspaces.selectAllCurrentChanges', source: 'Modules', package: 'Neos.Neos')}</th>
```

2022-10-24 16:47 UTC, kdambekalns commented on Neos.Neos/Resources/Private/Translations/en/Modules.xlf
> +			<trans-unit id="workspaces.checkbox.label">
```suggestion
			<trans-unit id="workspaces.selectAllCurrentChanges">
```

2022-10-24 17:51 UTC, mhsdesign approved these changes

2022-10-25 06:40 UTC, kdambekalns approved these changes

2022-10-25 06:41 UTC, merged