FEATURE: Add Neos.Fusion:Wrapper
neos/neos-development-collection pull request #4039
Opened 2023-02-15 14:28 UTC by jonnitto

If a `tagName` is given the `content` is wrapped in an HTML tag with the given tag. Otherwise, the content is returned as is.

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

2023-02-15 22:40 UTC, mhsdesign requested changes
I think we still need to work on the naming maybe something like `Neos.Fusion:TagOrContent`, while I agree that It sounds a bit too expressive (in the negative way).
I think that since it will not be used that often it still serves the purpose.

2023-02-16 13:54 UTC, mficzel commented
I wonder why not use a processor in this case.  Is this a common case we should solve as core feature or something one does project specific.

```
content = ... stuff
content.@process.wrap = Neos.Fusion:Tag
content.@process.wrap.@if.hasTagName = ${tagName}
content.@process.wrap.tagName = ${tagName}
content.@process.wrap.content = ${value}
```

2023-02-16 17:53 UTC, mhsdesign commented
hmm i see @mficzel point too, @jonnitto do you have a specific usecase at hand where one would like to have a Tag or a Content?

2023-02-16 18:32 UTC, jonnitto commented
`TagOrContent` is misleading, as it can both have content. The first idea was to expand the `Fusion:Tag` with the feature to also pass a falsy value as `tagName` and get only the content back. And yes, many people do something similar to this, but often in a quite dangerous way.

2023-04-01 14:01 UTC, mhsdesign commented
One could also use:

```
foo = Neos.Fusion:Tag {
    tagName = ${tagName}
    content = ${content}
    @process.onlyContent = ${this.tagName ? value : this.content}
}
```

And after rethinking it i would rather not have this proposed prototype for this super rare edgecase in the core.

Would you be okay with closing it?

2023-06-27 13:01 UTC, closed without merging