TASK: Use NodeTypes folder in core packages
neos/neos-development-collection pull request #4116
Opened 2023-03-16 03:24 UTC by Sebobo

**Upgrade instructions**

Not breaking

**Review instructions**

All nodetypes should still be loaded

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

2023-03-16 13:57 UTC, mhsdesign commented
Now we have a lot of unrelated style fixes in this pr ... @markusguenther

2023-03-16 15:37 UTC, mhsdesign requested changes, later dismissed
Lets keep the style ci stuff separate - the ci just went maniac ^^
https://github.com/neos/neos-development-collection/pull/4116#issuecomment-1472026304

2023-03-31 09:47 UTC, ahaeslich approved these changes

2023-03-31 09:48 UTC, ahaeslich commented
Fine by reading and ignoring all the style ci stuff ;)

2023-03-31 11:57 UTC, markusguenther approved these changes

2023-04-01 10:33 UTC, merged