!!! BUGFIX: DocumentUriProjection doesn't respect fallback nodes; NodePropertiesWereSet contains affectedDimensionSpacePoints
neos/neos-development-collection pull request #4266
Opened 2023-05-07 18:18 UTC by skurfuerst

Extending the NodePropertiesWereSet event is useful for some projections which are not interested in OriginDimensionSpacePoints, but need to know where a property value is applied (like the DocumentUriPathProjection).

This change is BREAKING because it updates the event payload of NodePropertiesWereSet. To update your event store, run:

./flow migrateEvents:fillAffectedDimensionSpacePointsInNodePropertiesWereSet

We also fix the DocumentUriPathProjection alongside.

Resolves: #4265
Resolves: #4256

2023-05-08 06:14 UTC, dlubitz commented
Looks good by reading. Will try it within next days. 
Just one test is failing due to the changes.

2023-05-08 09:11 UTC, ahaeslich requested changes

2023-05-08 09:11 UTC, ahaeslich commented on Neos.ContentRepository.Core/Classes/Feature/NodeModification/Event/NodePropertiesWereSet.php
> +        public readonly DimensionSpacePointSet $affectedDimensionSpacePoints,
There are two other places in the current code base where `NodePropertiesWereSet` is initialized, which are not addressed in this MR:

- `Neos\ContentRepository\StructureAdjustment\Adjustment\PropertyAdjustment->publishNodePropertiesWereSet()`
- `Neos\ContentRepository\LegacyNodeMigration\NodeDataToEventsProcessor->createNodeVariant()`

2023-05-08 09:11 UTC, ahaeslich commented on Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
> +        $this->nodeAuthorizationService = $this->objectManager->get(AuthorizationService::class);
This is a duplicate of the next line
```suggestion
```

2023-05-08 09:16 UTC, skurfuerst commented on Neos.ContentRepository.Core/Classes/Feature/NodeModification/Event/NodePropertiesWereSet.php
> +        public readonly DimensionSpacePointSet $affectedDimensionSpacePoints,
good catch :) thanks!

2023-05-09 18:27 UTC, skurfuerst commented on Neos.ContentRepository.Core/Classes/Feature/NodeModification/Event/NodePropertiesWereSet.php
> +        public readonly DimensionSpacePointSet $affectedDimensionSpacePoints,
done

2023-05-09 18:27 UTC, skurfuerst commented on Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
> +        $this->nodeAuthorizationService = $this->objectManager->get(AuthorizationService::class);
done

2023-05-09 18:28 UTC, skurfuerst commented
let's hope CI runs through now, then this would be merge ready IMHO. Tests locally run though :)

Thanks everybody!

2023-05-09 18:50 UTC, ahaeslich commented
> let's hope CI runs through now

They won't due to the recent dependency changes in https://github.com/neos/flow-development-collection/commits/9.0

2023-05-10 05:52 UTC, ahaeslich approved these changes
Tested the changes in our project 👍 💖

2023-05-10 17:23 UTC, merged