BUGFIX: RenderAttributesTrait allows Stringable objects
neos/neos-development-collection pull request #4267
Opened 2023-05-08 15:26 UTC by gjwnc

RenderAttributesTrait converts Stringable objects to strings via `__toString()`

related: #4225 

**Upgrade instructions**

Not sure what to write here :thinking: 

**Review instructions**

Up until 8.3 it was possible to use EelHelpers with a fluent interface like API for attributes. E.g. the following was working fine in fusion afx:
```
class={[block.element('subline').modifier('light')]}
```
The variable `block` is an EelHelper which returns `self`. In 8.3 this fails with an Exception
```
$attributes may contain values of type array<string|bool|null> type: array...
```
The reason is, that with PR #4225, in `RenderAttributesTrait` there are two different ways the object is processed:
1. In case `$attributeValue` is not an array, e.g. an object, it is basically converted to a string
2. In case of an array it is checked if `$attributeValuePart` is actually of type plain string, boolean or null. In case  of an object an exception is raised. This exception then breaks the previous behaviour in case of a `\Stringable` object.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

2023-05-08 15:31 UTC, mhsdesign commented on Neos.Fusion/Classes/Service/RenderAttributesTrait.php
> +                    if ($attributeValuePart instanceof \Stringable) {
is `method_callable($attributeValuePart, '__toString')` more versatile?

2023-05-08 15:38 UTC, mhsdesign requested changes
and the exception message and doc block needs to be adjusted to include \Stringable

> $attributes may contain values of type array<string|bool|null|\Stringable>

2023-05-08 17:50 UTC, gjwnc commented on Neos.Fusion/Classes/Service/RenderAttributesTrait.php
> +                    if ($attributeValuePart instanceof \Stringable) {
It depends on which php version should be supported. Because Neos/Flow 8.x requires php 8.x I thought this would be the way to go, since every class implementing the magic method `__toString` is implicitly a `Stringable`, i.e. in case of php8 your example should be equivalent to instanceof.
Shall I change it anyway?

2023-05-08 17:52 UTC, mhsdesign commented on Neos.Fusion/Classes/Service/RenderAttributesTrait.php
> +                    if ($attributeValuePart instanceof \Stringable) {
no i wasnt sure of the implicit magic :D so fine with me 🔥 thanks for the research

2023-05-08 17:55 UTC, gjwnc commented
> and the exception message and doc block needs to be adjusted to include \Stringable
> 
> > $attributes may contain values of type array<string|bool|null|\Stringable>

Done :heavy_check_mark:

2023-05-08 18:03 UTC, mhsdesign commented
Thanks ;) May i ask yet another thing? ^^
A test please :D (see https://github.com/neos/neos-development-collection/pull/4225)

if not ill add one later ...

2023-05-09 07:00 UTC, gjwnc commented
> Thanks ;) May i ask yet another thing? ^^ A test please :D (see #4225)

I've added the test case too. Please have a look.

2023-05-09 09:33 UTC, mhsdesign approved these changes
Thanks for the adjustments ;)

2023-05-30 12:34 UTC, dlubitz approved these changes

2023-05-30 12:37 UTC, merged