9.0 FEATURE: Persist NodeTypeName in DocumentUriPathProjection
neos/neos-development-collection pull request #4276
Opened 2023-05-11 17:56 UTC by dlubitz

Adds an additional field for the NodeTypeName of the NodeAggregate. This is needed for further processing of the DocumentNodeInfo for redirect handling.

2023-05-11 18:08 UTC, skurfuerst requested changes
hey, thanks for your change :) I added some comments to make it less breaking.

all the best,
Sebastian

2023-05-11 18:08 UTC, skurfuerst commented on Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/Event/RootNodeAggregateDimensionsWereUpdated.php
> +        public readonly NodeTypeName $nodeTypeName,
we cannot update the event payload here - such a change is very breaking. Why do you need this? You can simply copy the node type name from the existing root(s) :)

2023-05-11 18:08 UTC, skurfuerst commented on Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/Event/RootNodeAggregateDimensionsWereUpdated.php
> +            NodeTypeName::fromString($values['nodeTypeName'] ?? 'Neos.Neos:Sites'),
the CR does not depend on Neos.Neos:Sites

2023-05-11 18:08 UTC, skurfuerst commented on Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
> +                'nodeTypeName' => $event->nodeTypeName->value,
before deleting, I'd read the node type name from the projection here, so this way you do not need it in nthe event.

2023-05-11 18:30 UTC, dlubitz commented
Thanks @skurfuerst, I did the changes you suggested.

2023-05-12 05:40 UTC, skurfuerst commented
Awesome! I will review again today around noon.

2023-05-13 05:19 UTC, bwaidelich commented
Just looking at this briefly without going into the details, I failed to understand why this is needed?
Could you add a little explaining phrase to the description? (I fully trust you on this one ofc, but I'm curious and others might be too)

2023-05-13 08:56 UTC, dlubitz commented
> Just looking at this briefly without going into the details, I failed to understand why this is needed? Could you add a little explaining phrase to the description? (I fully trust you on this one ofc, but I'm curious and others might be too)

A added some more background information to the description.

2023-05-15 10:48 UTC, skurfuerst commented
looks all good, we should only extend the tests at https://github.com/neos/neos-development-collection/tree/9.0/Neos.Neos/Tests/Behavior/Features/FrontendRouting as well. Do you want to do it in this PR or in a separate one? :) 

All the best,
Sebastian

2023-05-15 10:48 UTC, skurfuerst approved these changes

2023-05-15 12:16 UTC, dlubitz commented
@skurfuerst Sure, I'll add some tests. Shall I extend the existing ones? Or shall we add dedicated tests for the nodetypes?

2023-05-15 14:21 UTC, skurfuerst commented
@dlubitz I do not have a clear preference here - so do what fits best for you :) 

All the best,
Sebastian

2023-05-15 15:44 UTC, dlubitz commented
@skurfuerst I've added/changed some tests to cover the new feature. Luckily this showed up an issue with the NodeTypeName changes.

2023-05-16 16:56 UTC, skurfuerst approved these changes
really cool @dlubitz :) I think this can be merged, wdyt?

2023-05-16 16:57 UTC, kitsunet approved these changes
Seems useful to me!

2023-05-16 16:57 UTC, merged