TASK: Remove `Neos.Node.inBackend()` eel helper
neos/neos-development-collection pull request #4542
Opened 2023-09-20 16:45 UTC by mficzel

It was deprecated in https://github.com/neos/neos-development-collection/pull/4505 in favor of `${userInterfaceMode.isEdit}`. Since the ui is adjusted in https://github.com/neos/neos-ui/pull/3618 it can now be removed.

Relates: #4086

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

2023-09-20 18:33 UTC, mhsdesign approved these changes
👍

2023-09-20 19:30 UTC, ahaeslich reviewed
I just wondered: do we want to keep `Neos.Node.isLive()` or did we discuss to remove this Eel Helper as well?

2023-09-20 19:30 UTC, ahaeslich commented on Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
> -     * @deprecated Remove before Neos 9.0 !!! Use ${userInterfaceMode.isEdit || userInterfaceMode.isPreview} instead
Wasn't it replaced by `renderingMode.isEdit` and `renderingMode.isPreview`? Should that be corrected in the merge request description?

2023-09-20 19:33 UTC, mhsdesign requested changes
yes good point we want to remove the `Neos.Node.isLive()` - i didnt know it existed ;)

2023-09-20 19:42 UTC, ahaeslich commented
... and if we remove `Neos.Node.isLive()` we need to adjust `Neos.Seo`. And I guess there might be an outdated `rector` migration.

2023-09-20 21:31 UTC, mhsdesign approved these changes

2023-09-21 06:52 UTC, ahaeslich approved these changes

2023-09-21 06:56 UTC, merged

2023-09-21 08:26 UTC, ahaeslich commented
Ah forgot that @mficzel already adjusted the rector migrations in https://github.com/neos/rector/pull/22 🤦 

I did adjust Neos.Seo where we introduced `Neos.Node.isLive()`: https://github.com/neos/neos-seo/pull/179.