TASK: Make the `ImageInterfaceArrayPresenter` required by the ui the …
neos/neos-development-collection pull request #4637
Opened 2023-10-22 07:48 UTC by mhsdesign

…default one

see https://github.com/neos/neos-ui/blob/70ab40793e291784bb01d18223180855c96e52d3/Configuration/Settings.yaml#L23

**Upgrade instructions**

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

2023-10-23 12:14 UTC, bwaidelich commented
can you add more context?
Why is this change needed?

2023-10-23 12:36 UTC, mhsdesign commented
this implementation was probably required by the old neos ui, so the "new" ui overrides this value.

Instead of having this configuration differently at two places im just cleaning up ;)

2023-10-23 12:44 UTC, kitsunet commented
Careful :D this assumption is AFAIK wrong, the point of the default is to work with serialising into string columsn of a DB (that is json doctrine type), the array representation is sepcific for the UI and should IMHO never be the default

2023-10-23 12:44 UTC, kitsunet requested changes
see comment before, I think this shouldn't be changed

2023-11-11 18:21 UTC, mhsdesign commented
Hmm I don’t fully understand aren’t these type converters only for the uni in neos 9 (and when the ui is installed this converter will be used either way…)

2024-01-13 16:08 UTC, mhsdesign commented
@kitsunet i think my proposal is correct and this can be merged without any negative side effects. or did I oversaw something?

2024-05-20 10:04 UTC, grebaldi commented
I agree with @mhsdesign. The UI should be the only place that's using this configuration, and it overrides  it anyway.

In the long run, it'd be sensible to move such configuration to the UI repo imho. There are a couple of places like this.

2024-05-20 10:09 UTC, kitsunet commented
Yep checked the whole situation, I confused what you wanted to do. Seems fine like this.

2024-05-20 10:31 UTC, mhsdesign commented
then lets merge ;) (Then i have one more slot open for $stuff :D)

20 ninjas at a time.

2024-05-20 10:49 UTC, grebaldi approved these changes

2024-05-20 13:39 UTC, kitsunet approved these changes

2024-05-20 13:39 UTC, merged