BUGFIX: Use the new version 3.0 of the setup tool
neos/neos-development-collection pull request #4803
Opened 2023-12-14 16:07 UTC by markusguenther

2023-12-14 16:27 UTC, markusguenther commented
https://github.com/neos/neos-development-distribution/pull/102

2023-12-14 16:33 UTC, markusguenther commented
After all of that changes, we need to adjust the docs.neos.io guides.

2023-12-15 07:10 UTC, crydotsnake approved these changes

2023-12-15 10:34 UTC, mhsdesign commented
hmm i would instead prefer to remove this dependency from the dev-collection. Its needless here as the base dist and dev dist require it already.

Also this pr should target 8.0 please as the problem also exists for 8.0

2023-12-15 10:56 UTC, kitsunet commented
yeah agree, can go IMHO.

2023-12-15 11:49 UTC, kdambekalns requested changes
And `.composer.json` must be adjusted, too.

https://github.com/neos/neos-development-collection/blob/bugfix/use-new-setup/.composer.json#L8

2023-12-15 12:00 UTC, mhsdesign commented
there is the ComposerManifestMerger in the build essentials dir which should merge the `.composer.json` ;)

2023-12-15 12:11 UTC, markusguenther commented
Ok will adjust that, thanks for the feedback. :)

2023-12-15 18:24 UTC, markusguenther commented
The PR has been adjusted and the neos-base-distribution and the neos-development-distribution are fine as well :)

2023-12-17 11:13 UTC, mhsdesign approved these changes
Thank you ;) Looks exactly like i had in mind ;)

2023-12-19 16:10 UTC, kdambekalns approved these changes

2023-12-19 16:11 UTC, crydotsnake approved these changes

2023-12-19 16:12 UTC, merged