Bugfix/5116: frontend fix for multiple imports of the same remote asset
neos/neos-development-collection pull request #5117
Opened 2024-06-03 09:03 UTC by so-grimm

This is a frontend fix for #5116 and prevents users from triggering multiple import processes for the same remote asset. It is not a sufficient fix to only prevent this in the frontend though, since it doesn't catch it, if two or more different users trigger the import for the same asset at the same time.

Changes:
- `select.js`: add data attribute `data-import-in-process` to asset once import process has started and remove it when import is done
- `select.js`: check for new data attribute and only start import process if attribute does not exist
- `select.js`: add notification to inform user that asset is being imported
- `select.js`: add notification as warning for user if import is already in process
- `Main.xlf`: add new notification messages for english
- `Default.html`: add id for notification container to be able to send notifications to it via js
- `Configuration.js`: update `hasConfiguration` after configuration object was created, because otherwise it will always be false and the translations don't work

`related:` https://github.com/neos/neos-development-collection/issues/5116

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

2024-06-03 10:32 UTC, ahaeslich commented on Neos.Media.Browser/Resources/Public/JavaScript/select.js
> +													$(this).remove('data-import-in-process')
Shouldn't this be `removeAttr` instead of `remove`?

2024-06-03 10:43 UTC, ahaeslich approved these changes
+1 by reading

2024-06-03 10:57 UTC, Sebobo requested changes
Thx! Also for fixing the configuration issue.

We should just, when we anyway adjust the code not use more jQuery, but replace where its easy.

2024-06-03 10:57 UTC, Sebobo commented on Neos.Media.Browser/Resources/Public/JavaScript/select.js
> +										if ($(this).attr('data-import-in-process') !== 'true') {
Can you please when you anyway update the code also replace jQuery code with Vanilla JS ❤️

2024-06-05 09:50 UTC, dlubitz approved these changes
Thank you for this. Looks good to me by reading.

2024-06-05 10:13 UTC, ahaeslich approved these changes

2024-06-05 10:13 UTC, Sebobo approved these changes
⭐️⭐️⭐️⭐️⭐️

2024-06-05 10:13 UTC, merged

2024-07-12 17:15 UTC, so-grimm commented
I noticed something strange today relating to this bugfix. In this PR I made changes to the Neos.Media.Browser package, but also to the Neos.Neos package. I assumed that assets would be bundled automatically via pipeline, so I didn't bundle them. Now I noticed that the Neos.Media.Browser changes are working just fine (because the are included directly and don't need bundling), but the Neos.Neos changes are not working, because they need to be bundled and that didn't happen. Without it, the notification messages don't show any text.
Can someone tell me how the workflow is supposed to work? Should I have bundled the assets myself and pushed them? And what do we do about it now? Would be great if someone could help me with that.

2025-01-09 10:33 UTC, dlubitz commented
Very likely this change caused a bug in the selection of images out of the list view:
https://github.com/neos/neos-development-collection/issues/5430