FEATURE: Add image helper and render image dimensions in image tag attributes
neos/neos-development-collection pull request #5131
Opened 2024-06-05 13:44 UTC by Sebobo

With this change a new image helper is introduced in Neos.Media which allows creating a thumbnail and using its various properties in Fusion object. This way the actual size of a thumbnail can be rendered into the HTML attributes.
Until now we only had the uri from the ImageUri helper and component.

**Review instructions**

Adjust the image prototype renderer in the Demo like this:
```
prototype(Neos.Demo:Content.Image) < prototype(Neos.Neos:ContentComponent) {
    renderer = afx`
        <figure>
            <Neos.Neos:ImageTag
                asset={q(node).property('image')}
                width={900}
                height={200}
                allowUpScaling={true}
            />
        </figure>
    `
//    renderer = afx`<Neos.Demo:Presentation.Image {...props} />`
}
```

The resulting image should have with and height properties of the generated thumbnail and not the ones of the original.

I'm not 100% sure if we could break something with this change if somebody modified the ImageTag prototype. 
We can also target 9.0 if the anybody thinks this would be better.

2024-09-05 21:08 UTC, crydotsnake approved these changes
Codewise and functionality wise its working great for me!

2025-10-07 12:55 UTC, mhsdesign reviewed
i think we should have this explicitly in 9.x and not upmerged

2025-10-07 12:55 UTC, mhsdesign commented on Neos.Neos/Resources/Private/Fusion/Prototypes/ImageTag.fusion
> +# ImageTag object works exactly the same way as image ViewHelper in the Neos.Media package
i know its not your comment but that comment doesnt help much ... i dont know how the ViewHelper works and i dont want to :D

2025-10-07 12:55 UTC, mhsdesign commented on Neos.Neos/Resources/Private/Fusion/Prototypes/ImageTag.fusion
> +  @context.thumbnail = ${Neos.Media.Image.createThumbnail(
is that correct that Neos.Neos has a fusion prototype with a Neos.Media dependency?

Why not have the helper in Neos or the fusion prototype in Neos.Media?

im just wondering.

2025-10-07 13:18 UTC, mficzel requested changes
Generally agree and like the change but i would prefer async as default for thumbnails.

2025-10-07 13:18 UTC, mficzel commented on Neos.Neos/Resources/Private/Fusion/Prototypes/ImageTag.fusion
> +  async = false
can we make async true as default?

2025-10-08 07:41 UTC, Sebobo commented on Neos.Neos/Resources/Private/Fusion/Prototypes/ImageTag.fusion
> +  async = false
I just moved the code from the other file, don't want to change the default.

2025-10-08 07:43 UTC, Sebobo commented on Neos.Neos/Resources/Private/Fusion/Prototypes/ImageTag.fusion
> +  @context.thumbnail = ${Neos.Media.Image.createThumbnail(
Media has no dependency on Fusion but already eel helpers for assets. I would keep it like that.

2025-10-08 13:58 UTC, mficzel approved these changes

2025-10-09 06:48 UTC, merged