FEATURE: New workspace overview UX
neos/neos-development-collection pull request #5132
Opened 2024-06-05 13:47 UTC by Sebobo

A new UX for the workspace overview based on the package https://github.com/Sebobo/Shel.Neos.WorkspaceModule

**Upgrade instructions**

TODO

**Review instructions**

TODO

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

2024-10-30 14:19 UTC, mhsdesign commented
Annnd the new cr selector got lost during the rewrite:

<img width="657" alt="image" src="https://github.com/user-attachments/assets/65b013c2-5a14-41d7-bd47-a9372f2c05ea">

2024-10-31 21:32 UTC, mhsdesign commented
FYI i moved all adjustments don to the `WorkspaceService` into this separate PR https://github.com/neos/neos-development-collection/pull/5334 so we can discuss them and also write tests for them etc ...

When that is merged ill update this pr

2024-12-05 15:08 UTC, bwaidelich reviewed
Just some, partly nitpicky, comments :)

2024-12-05 15:08 UTC, bwaidelich commented on Neos.Workspace.Ui/Classes/ViewModel/ChangeItem.php
> +        public ContentChangeItems      $contentChanges,
Nitpick, but we don't really do these aligned arguments any more, because they don't really increase readability and lead to larger diffs when a new param is introduced that exceeds the previous max length
```suggestion
        public string $serializedNodeAddress,
        public bool $hidden,
        public bool $isRemoved,
        public bool $isNew,
        public bool $isMoved,
        public array $dimensions,
        public ?string $lastModificationDateTime,
        public ?string $createdDateTime,
        public string $label,
        public string $icon,
        public ContentChangeItems $contentChanges,
```

2024-12-05 15:08 UTC, bwaidelich commented on Neos.Workspace.Ui/Classes/ViewModel/ConfirmDeleteWorkspaceRoleAssignmentFormData.php
> +    }
```suggestion
    public function __construct(
        public WorkspaceName $workspaceName,
        public WorkspaceTitle $workspaceTitle,
        public string $subjectValue,
        public string $subjectType,
    ) {
    }
```

2024-12-05 15:08 UTC, bwaidelich commented on Neos.Workspace.Ui/Classes/ViewModel/CreateWorkspaceRoleAssignmentFormData.php
> +        public array          $roleOptions
```suggestion
        public WorkspaceName $workspaceName,
        public WorkspaceTitle $workspaceTitle,
        /**
         * Options for the workspaceManager selector where the key is the user identifier and the value is the user name.
         * @var array<string, string>
         */
        public array $userOptions,
        /**
         * Options for the workspaceManager selector where the value is the group.
         * @var array<string>
         */
        public array $groupOptions,
        /**
         * TODO: translate subject type labels?
         * Options for the workspaceManager selector where the key is the subject type and the value is the subject label.
         * @var array<string>
         */
        public array $subjectTypeOptions,
        /**
         * TODO: translate role labels?
         * Options for the workspaceManager selector where the key is the role identifier and the value is the role label.
         * @var array<string, string>
         */
        public array $roleOptions
```

2024-12-05 15:08 UTC, bwaidelich commented on Neos.Workspace.Ui/Classes/ViewModel/EditWorkspaceFormData.php
> +    {
doc comments for promoted properties must be put `@param` not `@var` annotations

```suggestion
    /**
     * @param array<string, string> $baseWorkspaceOptions Options for the baseWorkspace selector where the key is the workspace name and the value is the workspace title.
     */
    public function __construct(
        public WorkspaceName $workspaceName,
        public WorkspaceTitle $workspaceTitle,
        public WorkspaceDescription $workspaceDescription,
        public bool $workspaceHasChanges,
        public WorkspaceName $baseWorkspaceName,
        public array $baseWorkspaceOptions,
    ) {
```

2024-12-05 15:08 UTC, bwaidelich commented on Neos.Workspace.Ui/Classes/ViewModel/EditWorkspaceRoleAssignmentsFormData.php
> +    {
```suggestion
    /**
     * @param array<RoleAssignmentListItem> $roleAssignments
     */
    public function __construct(
        public WorkspaceName $workspaceName,
        public WorkspaceTitle $workspaceTitle,
        public bool $roleAssignmentsEditable,
        public array $roleAssignments,
    ) {
```

2024-12-05 15:08 UTC, bwaidelich commented on Neos.Neos/Classes/Domain/Service/WorkspaceService.php
> +        }
My bad, but this check is obsolete with #5397

```suggestion
```

2024-12-05 15:08 UTC, bwaidelich commented on Neos.Neos/Classes/Domain/Service/WorkspaceService.php
> +        }
obsolete with #5397

```suggestion
```

2024-12-07 16:06 UTC, mhsdesign commented
I corrected the workspace service so it works more like anticipated (and like in 8.3) in https://github.com/neos/neos-development-collection/pull/5334

One thing I dont understand is if we really want the change that a neos administrator can read, write and mange every workspace? 

```php
        if ($userIsAdministrator) {
            return WorkspacePermissions::all('User is Neos Administrator');
        }
```

That was change by @JamesAlias see https://github.com/neos/neos-development-collection/commit/916e51009e9c97b42aa32372b94d149a2022faeb

Currently admins only are managers (and cannot read the workspace) unless they promote themselves to anything else - though i see that might be the logic flaw.

EDIT: We reverted that change as admins are only allowed to be managers as escape hatch

2024-12-12 10:58 UTC, mhsdesign commented
Okay, i extracted all the workspace service adjustments and wrote tests that it works now: https://github.com/neos/neos-development-collection/pull/5334 indeed some parts were odd and needed fixing.

That is merged into 9.0 and i also merged that back into there and adjusted this pr to the new method signature.

That means the ci should have a chance to get this green soonish as there are no core changes anymore.
Only that it seems all the new code is not really written with phpstan :D It really helps to run

```
composer run lint:phpstan
```

every once in a while ^^

Currently there a lot of possible null access bugs.

2024-12-17 09:15 UTC, mhsdesign commented
As discussed in the daily today i proposed to revert the role assignment ui part instead for this pr and have it done separately:

https://github.com/neos/neos-development-collection/pull/5132/commits/4aed44146bf8de69d6b0809c77b6e110d2409712

i argued against a feature flag, because some buttons are currently not working for the assignments and i hope that when reintroducing this change in a new pr the code can be better reviewed and tested.

Also by fully removing this code for now we also keep this pr slimmer and more easy to review what is great as well.

reverts all actions:

- editWorkspaceRoleAssignmentsAction
- createWorkspaceRoleAssignmentAction
- addWorkspaceRoleAssignmentAction
- confirmDeleteWorkspaceRoleAssignmentAction
- deleteWorkspaceRoleAssignmentAction

(sorry robert :D)

-----

one more thing: Sebastian will attempt to reimplement a basic kind of access control again (basically mapping the 'old' internal / private functionality on the new model) - but i would be fine to do this in a followup pr too.

Currently the Neos beta contains the Neos 8 workspace module in super slimmed down and broken, having this pr merged - even without any acl (which is NOT implemented in the current beta) would already be a step forward. And merging this right now would give us maybe still the chance to get the reverted full acl (edit role assignments) running.
In case we dont get the full acl working soon, we should then at least ship with Neos 9.0 the old internal & private functionality.

-----

So in order to get this merged id say we can begin with the bug hunting and all features are followups?
I have a bug to begin: The cancel button (for creation) doesnt work.

2024-12-17 10:10 UTC, mhsdesign requested changes
okay i had a dedicated look at the php and added  a few comments i like to discuss.

Additionally there are 25!!! NEW todos in the code, its obvious that some todos will be unresolved, but lets have a look at those - and maybe remove todos already that are none?

(quick way to find todos:)
```
git diff -U0 origin/9.0...HEAD > ../myCurrent.diff
```
search `myCurrent.diff` for `^\+.*todo` :D

2024-12-17 10:10 UTC, mhsdesign commented on Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
>          /** @todo do something else
whatever this did before (possibly in 8.3) we should reimplement that

2024-12-17 10:10 UTC, mhsdesign commented on Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
> +            if($change->deleted) $changesCount['removed']++;
this codestyle is not psr12 we always use braces

2024-12-17 10:10 UTC, mhsdesign commented on Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
> +                // todo implement support for change node type!!! Because originDimensionSpacePoint is null currently for that case.
this might be solvable by https://github.com/neos/neos-development-collection/pull/5395 ... lets see

2024-12-17 10:10 UTC, mhsdesign commented on Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
> +        $packageKey = 'Neos.Neos';
why is this translation logic needed here? its duplicated from `\Neos\ContentRepositoryRegistry\Configuration\NodeTypeEnrichmentService::splitIdentifier`

and was introduced via b830ee8a2d88be1d6cc81c41667c85f1ddb5dcdd

2024-12-17 10:10 UTC, mhsdesign commented on Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
> +        });
this is kinda odd, but makes sense i guess?

Introduced via 384b6e2ebfcfc30e618cb16c0e085636b9dc487a

2024-12-17 10:10 UTC, mhsdesign commented on Neos.Workspace.Ui/Classes/Mvc/HtmxRequestPattern.php
> +final class HtmxRequestPattern implements RequestPatternInterface
for "framework" like things like these, maybe we should add a little docs why this is needed? This will possibly be moved to Flow or Neos at some point right?

2024-12-17 10:10 UTC, mhsdesign commented on Neos.Workspace.Ui/Classes/ViewModel/ContentChanges/ContentChange.php
> +readonly class ContentChange
i guess this should be either abstract or an interface?, or not needed at all if we uses unions

2024-12-17 10:10 UTC, mhsdesign commented on Neos.Workspace.Ui/Documentation/UserStories.rst
this list needs to be carefully reviewed if its still up to date with the Neos 9 workspace implementation.

Especially there is no definition for shared or internal:

> The visibility of the workspace (e.g. "Shared", "Private") and its access control list (ACL)

and they are no concepts for the current model either

--------

in general this readme might be better off as functional test - not using the workspace ui - but by testing the flow actions?

Behaviour in delete workspace is already different, as workspace with changes cannot be deleted see `throwStatus(403, 'Workspace has unpublished nodes');`.

So before merge, this list needs to be up to date or enforced, or we put this into a discuss post or something were we rather discuss the behaviour:)

2024-12-17 10:10 UTC, mhsdesign commented on Neos.Workspace.Ui/Resources/Private/Fusion/Features/Workspace/Modals/Edit.fusion
> +  /// array<workspaceName: string, workspaceTitle: string>
sidetrack: spaces are not allowed here technically but we probably need to refine the proposal https://discuss.neos.io/t/documenting-fusion/6056/35

2024-12-17 10:10 UTC, mhsdesign commented on Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
>          $this->view->assign('displayContentRepositorySelector', $numberOfContentRepositories > 1);
this selector, and the ability to choose between content repositories, got lost (see https://github.com/neos/neos-development-collection/pull/5132/#issuecomment-2447319888)

we can probably live without this. Though we then should fully remove the unused variables?

2024-12-18 12:32 UTC, mhsdesign commented on Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
> +            $this->indexAction();
regarding all changes in e94d23a22fab844d5921a446bc640a4d1f4bcce9 we can instead of calling the other action directly use flow `$this->forward('index')` which does basically that but in a "correct" way

2024-12-18 12:36 UTC, mhsdesign commented on Neos.Workspace.Ui/Resources/Private/Fusion/Features/Review/Actions/Redirects.fusion
> +Neos.Workspace.Ui.WorkspaceController.discardWorkspace < Neos.Workspace.Ui.WorkspaceController.review
copy path in fusion is deprecated and its not a performant behaviour (as it literally copies the whole thing over and over during parsing for the runtime)

I removed all occurrences from the code base and dont think its necessary here.

How about
A: Use a dedicated prototype
B: instead of using the default delegating behaviour of the FusionView, set the entry path to `Neos.Workspace.Ui.WorkspaceController` and there use a match which uses `request.controllerActionName`

2024-12-18 13:14 UTC, Sebobo commented on Neos.Workspace.Ui/Resources/Private/Fusion/Features/Review/Actions/Redirects.fusion
> +Neos.Workspace.Ui.WorkspaceController.discardWorkspace < Neos.Workspace.Ui.WorkspaceController.review
We don't need this if `forward` works properly

2024-12-18 14:45 UTC, Sebobo commented on Neos.Workspace.Ui/Resources/Private/Fusion/Features/Review/Actions/Redirects.fusion
> +Neos.Workspace.Ui.WorkspaceController.discardWorkspace < Neos.Workspace.Ui.WorkspaceController.review
Yes I removed all of it again :)

2024-12-18 14:46 UTC, Sebobo commented on Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
> +            $this->indexAction();
Done

2024-12-18 15:04 UTC, Sebobo commented on Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
> +        });
With many workspaces it was uncomfortable to search for the live workspace in the dropdown, which is the most used one.

2024-12-18 15:05 UTC, Sebobo commented on Neos.Workspace.Ui/Classes/Mvc/HtmxRequestPattern.php
> +final class HtmxRequestPattern implements RequestPatternInterface
Yes as this can affect integrator code too.

2024-12-20 08:30 UTC, pKallert commented
Created PR for updating URL for new review in Neos UI: https://github.com/neos/neos-ui/pull/3904

2024-12-20 12:07 UTC, mhsdesign commented on Neos.Workspace.Ui/Classes/Mvc/HtmxRequestPattern.php
> +final class HtmxRequestPattern implements RequestPatternInterface
we discussed that if we want to support htmx for other modules as well we will probably create a dedicated framework code package for that. But for now its easiest to have it all in the ui code package and restrict it to only affect this package.

2024-12-20 12:16 UTC, Sebobo commented on Neos.Workspace.Ui/Classes/Mvc/HtmxRequestPattern.php
> +final class HtmxRequestPattern implements RequestPatternInterface
We did that yesterday already :)

2025-01-06 10:26 UTC, mhsdesign commented
I extracted the obsolete policy yaml removals into 

- https://github.com/neos/neos-development-collection/pull/5417
- https://github.com/neos/neos-development-collection/pull/5418

as i felt they were to big to include here and deserve some additional information.

They can be merged later.

2025-01-06 11:07 UTC, mhsdesign commented on Neos.Workspace.Ui/Resources/Private/Fusion/Features/Review/Components/ReviewDocumentTableRow.fusion
> +      @process.addQuery = ${value + '?node=' + document.document.documentNodeAddress}
will be fixed via https://github.com/neos/neos-development-collection/pull/5419

2025-01-06 11:10 UTC, mhsdesign commented on Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
> +                // todo implement support for change node type!!! Because originDimensionSpacePoint is null currently for that case.
hotfixed via https://github.com/neos/neos-development-collection/pull/5132/commits/c4eb48fb00f72f5f88af74f7368c6a2d13e477d1

2025-01-06 11:20 UTC, mhsdesign commented on Neos.Workspace.Ui/Classes/ViewModel/ContentChanges/ContentChange.php
> +readonly class ContentChange
Fixed via https://github.com/neos/neos-development-collection/pull/5132/commits/0e17338d5206b99b848b3d50e107cc3ebe23628a

2025-01-07 05:53 UTC, pKallert commented on Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
> +        $packageKey = 'Neos.Neos';
Could not find a better way to get the translations for the property labels here when using i18n - suggestions are welcome 😄

2025-01-08 12:05 UTC, mhsdesign commented on Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
> +        $packageKey = 'Neos.Neos';
I tested it now with `TranslationHelper()->translate()` and it works still. Its also a little hacky but less code duplication and we do it in other places too.

2025-01-08 16:53 UTC, mhsdesign approved these changes
Thanks to everyone who participated here or in all the discussions! Great to have this on the finish line!!!

I tested it out and fixed some bugs:
- [BUGFIX: Allow to edit workspaces if they contain changes](https://github.com/neos/neos-development-collection/pull/5132/commits/8a94d89d74ca2eac4f137871728435706fd19b59)
- [BUGFIX: Fix sorting glitch because the hot swapped WorkspaceTable](https://github.com/neos/neos-development-collection/pull/5132/commits/bfb52da796b4d0ec499dd449258975de5389a9b3)
- [BUGFIX: Show workspaces in overview if their parent workspace is no](https://github.com/neos/neos-development-collection/pull/5132/commits/f3fe1d08a61d0bbd78eedea1b4d15f1179358bea)

And also resolved the last todos or made a followup pr. The code is now polished and can be merged!! :)

2025-01-13 10:07 UTC, pKallert approved these changes
Tested locally and did not find any obvious issues

2025-01-13 10:07 UTC, merged