FEATURE: Improve user sorting behavior
neos/neos-development-collection pull request #5159
Opened 2024-06-22 20:05 UTC by crydotsnake

**Upgrade instructions**

_None_

**Review instructions**

I added this feature for 9.0 but since we want to release a Neos 8.4 i cherry-picked the commit so we have this feature already in Neos 8.4! For more details see: #4443 

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

2024-07-01 11:55 UTC, kitsunet approved these changes
Right, why not... But is this really all that is needed?

2024-07-01 11:59 UTC, mhsdesign commented on Neos.Neos/Resources/Public/Styles/Lite.css
wait a sec, this doesnt look particular light anymore ;) it seems it was not minified?

2024-07-01 12:12 UTC, kitsunet commented on Neos.Neos/Resources/Public/Styles/Lite.css
Huh, interesting

2024-07-01 13:14 UTC, crydotsnake commented on Neos.Neos/Resources/Public/Styles/Lite.css
I compiled everything again after the rebase 🤔.

2024-07-02 07:40 UTC, kitsunet requested changes
Realized just now, did you maybe not do `yarn build:production` ? That seems to work fine for me.

2024-07-02 12:38 UTC, crydotsnake commented
> Realized just now, did you maybe not do `yarn build:production` ? That seems to work fine for me.

Mh. I thought i exactly did that. I recompiled the files with `yarn build:production`

2024-08-18 15:54 UTC, crydotsnake commented
Why are the PHP Tests failing?

2024-08-26 11:34 UTC, kitsunet commented
I think the php errors are not your fault, but tahter a problem of 8.4 and behat...

2024-09-01 16:14 UTC, crydotsnake commented
Ready for review!

But PHP tests are still failing after a rebase..

2024-10-01 10:30 UTC, bwaidelich commented
@kitsunet I'm not sure why you blocked this, I assume the CSS/JS diff was too big. Is that solved now?

2024-10-01 10:38 UTC, kitsunet approved these changes
yep, fine fine!

2024-10-05 11:53 UTC, crydotsnake commented
@mhsdesign Please also have a look at it :) I had to rebase again.

2024-11-08 19:11 UTC, crydotsnake commented
@mhsdesign Ping :)

2024-12-17 09:10 UTC, crydotsnake commented
Hello @kitsunet @mhsdesign 

Would be awesome if you could take a look again!

I still have no idea why the tests are failing. Maybe a second rebase could help? 🤞🏽

2025-06-23 08:00 UTC, crydotsnake commented
Closed in favour of: #5584

2025-06-23 08:00 UTC, closed without merging